"""Added Premium Field

Revision ID: b16ce69e4b5b
Revises: a214be8ad63a
Create Date: 2024-01-02 09:35:04.959150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16ce69e4b5b'
down_revision = 'a214be8ad63a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_premium', sa.Boolean(), server_default=sa.text('0'), nullable=True))
    
    #* In this piece, we fill the existing users with 'is_premium=false', as they haven't bought the premium plan.
    with op.batch_alter_table('users', schema=None) as batch_op:
        is_premium = sa.table("users", sa.column("is_premium"))
        batch_op.execute(is_premium.update().values(is_premium=sa.text('0')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_premium')

    # ### end Alembic commands ###
